---
- hosts: test
  tasks:
    - name: Print Message
      debug:
        msg: Hello, Arpit Patel!!

  # install td-agent using yum module "fluentd_name" define in default as "td-agent"
    - name: Install Apache >= 2.4
      yum:
        name: httpd>=2.4
        state: present
