---
- hosts: test
  tasks:
    - name: Print Message
      debug:
        msg: Hello Ansible World
 # install td-agent 
    - name: Install td-agent
      become: true
      yum:
        name: td-agent
        state: present
