---
- hosts: test
  tasks:
    - name: Print Message
      debug:
        msg: Hello, Khush Patel!!

  # install td-agent using yum module "fluentd_name" define in default as "td-agent"
    - name: Install td-agent
      yum:
        name: td-agent
        state: present
